# Copyright (C) 2017 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).

# logger options
log_iter: 1000                # How often do you want to log loss and learning rate values during training

# optimization options
max_epoch: 100                # maximum number of training epochs
batch_size: 32                # batch size
weight_decay: 0.0001          # weight decay
beta1: 0.5                    # Adam parameter
beta2: 0.999                  # Adam parameter
lr: 0.001                     # initial learning rate
lr_policy: multi              # learning rate scheduler [constant/step/cos/multi]
iter_per_epoch: 2778          # iterations per epoch
lr_steps: [25,38]             # epochs to step learning rate
gamma: 0.1                    # how much to decay learning rate
warmup: linear                # warm up type
warmup_iters: 695             # warm up iterations
mixed_precision: True         # use automatic mixed precision training
random_seed: 42

# model options
trainer: Baseline             # trainer [UNIT/MUNIT/Baseline]
lane:
  backbone: 18                # resnet backbone for baseline
  pretrained: False           # use pretrained resnet backbone
  norm: bn                    # normalization layer [none/bn/in/ln]
  use_aux: True               # use segmentation loss [True/False]
  griding_num: 200            # number of column samples
  cls_num_per_lane: 18        # number of row anchors [TuSimple/WATO=56, CULane=18]
  num_lanes: 4                # max number of lanes
  sim_loss_w: 0.0             # lane similarity loss
  shp_loss_w: 0.0             # lane shape loss weight

# data options
input_dim_a: 3                # number of image channels [1/3]
input_dim_b: 3                # number of image channels [1/3]
input_height: 288             # resized image height
input_width: 800              # resized image width

# By convention, dataset A will be simulation, labelled data, while dataset B will be real-world without labels
dataset: CULane                       # real-world dataset [CULane/TuSimple]
dataA_root: /datasets/WATO_CULane     # dataset folder location for simulation images with labels
dataB_root: /datasets/CULane          # dataset folder location for real-world images without labels
