# Copyright (C) 2017 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).

# logger options
log_iter: 103                 # How often do you want to log loss and learning rate values during training

# optimization options
max_epoch: 150                # maximum number of training epochs
batch_size: 32                # batch size
weight_decay: 0.0001          # weight decay
beta1: 0.5                    # Adam parameter
beta2: 0.999                  # Adam parameter
lr: 0.0004                    # initial learning rate
lr_policy: cos                # learning rate scheduler [constant/step/cos]
iter_per_epoch: 103           # iterations per epoch
gamma: 0.1                    # how much to decay learning rate
warmup: linear                # warm up type
warmup_iters: 100             # warm up iterations
mixed_precision: True         # use automatic mixed precision training
multi_gpu: False              # use multi gpu training
random_seed: 42

# model options
trainer: Baseline             # trainer [UNIT/MUNIT/Baseline]
lane:
  backbone: 18                # resnet backbone for baseline
  pretrained: False           # use pretrained resnet backbone
  norm: bn                    # normalization layer [none/bn/in/ln]
  activ: relu                 # activation function [relu/lrelu/prelu/selu/tanh]
  use_aux: True               # use segmentation loss [True/False]
  use_cls: True               # predict lane classes [True/False]
  det_fc_size: 2048           # size of the detection fc layer
  cls_fc_size: 1024           # size of the classification fc layer
  griding_num: 100            # number of column samples
  num_anchors: 56             # number of row anchors [TuSimple/WATO=56, CULane=18]
  num_lanes: 4                # max number of lanes
  num_classes: 3              # number of classes (including no lane class) to predict [3/4]
  sim_loss_w: 1.0             # lane similarity loss
  shp_loss_w: 0.0             # lane shape loss weight
  cls_loss_w: 0.1             # lane classification loss weight

# data options
input_dim_a: 3                # number of image channels [1/3]
input_dim_b: 3                # number of image channels [1/3]
input_height: 288             # resized image height
input_width: 800              # resized image width

# By convention, dataset A will be simulation, labelled data, while dataset B will be real-world without labels
dataset: TuSimple                     # real-world dataset [CULane/TuSimple]
dataA_root: /datasets/WATO_TuSimple   # dataset folder location for simulation images with labels
dataB_root: /datasets/TuSimple        # dataset folder location for real-world images without labels
